### ISSUE TITLE
Is it possible to use the API if steam is installed as a flatpak?

### ISSUE THREAD

**Issue by pubnoconst** [Noxime/steamworks-rs#127]
In Linux, flatpak is quickly gaining popularity and many people are using flatpak to install steam. I am trying to write a tool to display network statistics of connected players in lobby using steamworks. 

When I am trying to initiate `Client`, I am getting the following error:
```
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
dlopen failed trying to load:
/home/u1/.steam/sdk64/steamclient.so
with error:
/home/u1/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /home/u1/.steam/sdk64/steamclient.so
thread 'main' panicked at 'Failed to initialize Steamworks API: InitFailed', src/main.rs:5:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
   3: core::result::Result<T,E>::expect
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1069:23
   4: rust_playground::main
             at ./src/main.rs:5:18
   5: core::ops::function::FnOnce::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The `sdk64` is located at `$HOME/.var/app/com.valvesoftware.Steam/.steam/sdk64` and there is a `steamclient.so` in there. There's also an `sdk32` in the same directory as `sdk64` 

Note that I have installed steam flatpak as a user which is why it is at `$HOME`. Destination might be simply `/var` if a user installs steam flatpak systemwide.

I have tried using LD_LIBRARY_PATH:
```
export LD_LIBRARY_PATH=$HOME/.var/app/com.valvesoftware.Steam/.steam/sdk64:$LD_LIBRARY_PATH
```
To find the same issue. 

Same with LD_PRELOAD:
```
$ LD_PRELOAD=$HOME/.var/app/com.valvesoftware.Steam/.steam/sdk64/steamclient.so cargo run -q
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
dlopen failed trying to load:
/home/u1/.steam/sdk64/steamclient.so
with error:
/home/u1/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /home/u1/.steam/sdk64/steamclient.so
thread 'main' panicked at 'Failed to initialize Steamworks API: InitFailed', src/main.rs:5:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by pubnoconst** [comment]
Fixed it with creating a symbolic link: `ln -s /home/u1/.var/app/com.valvesoftware.Steam/.steam/sdk64/steamclient.so /home/u1/.steam/sdk64/steamclient.so`
